
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Feb 07 01:29:12 CET 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MOD = 13;
  public static final int READ = 6;
  public static final int IDENT = 29;
  public static final int PLUS = 9;
  public static final int RBRACE = 24;
  public static final int RPAREN = 22;
  public static final int EQUAL = 16;
  public static final int CHAR = 30;
  public static final int SEMI = 17;
  public static final int POINT = 20;
  public static final int RETURN = 8;
  public static final int LBRACE = 23;
  public static final int LPAREN = 21;
  public static final int COLON = 19;
  public static final int LSQUAREBRACKET = 25;
  public static final int INC = 14;
  public static final int COMMA = 18;
  public static final int NUMBER = 28;
  public static final int EOF = 0;
  public static final int DIV = 12;
  public static final int PROG = 2;
  public static final int DEC = 15;
  public static final int MINUS = 10;
  public static final int CONST = 3;
  public static final int PRINT = 5;
  public static final int error = 1;
  public static final int NEW = 4;
  public static final int BOOL = 27;
  public static final int RSQUAREBRACKET = 26;
  public static final int MUL = 11;
  public static final int VOID = 7;
}

